#!/bin/bash
if [[ $(git remote -v | grep github.com) ]]; then
  echo "Commit Rules NOT enforced"
  exit 0
else
  echo "Commit Rules enforced"
fi

MSG_FILE=$1
FILE_CONTENT="$(cat $MSG_FILE)"

# Initialize constants here
export REGEX='^(PAYM+-+[0-9]+:) .+'
export ERROR_MSG="Commit message format must match regex \"$REGEX\""

if [[ $FILE_CONTENT =~ $REGEX ]]; then
	echo "Good commit!"
else
  echo "Bad commit \"$FILE_CONTENT\""
	echo $ERROR_MSG
	exit 1
fi

exit 0